### ISSUE TITLE
Non-existent version of moviepy in requirements.txt

### ISSUE THREAD

**Issue by bvobart** [yandex-research/navigan#1]
Hi Anton Cherepkov, Andrey Voynov, and Artem Babenko,

I'm doing research on linting and code quality practices in ML and am developing an automated tool to run static code analysis (Pylint with its default configuration) on a multitude of ML projects, yours included. 

I was pleased to find a `requirements.txt` file in your repo (many ML projects I've come across so far don't have one), but `pip install`ing it produces an error, stating that there is no `moviepy` version 0.1.3, which [is correct](https://pypi.org/project/moviepy/#history). The latest version of `moviepy` is 1.0.3.

Personally, I can work around it for my research, but for the sake of the reproducibility of your research, could you fix this please? Also, while you're busy, it might be a good idea to check whether the rest of the requirements have the versions that you intend them to have and have tested your code with.

https://github.com/yandex-research/navigan/blob/ad10a3018a4659dabc4f7eb392735310b876b5b6/requirements.txt#L9

**Comment by Anton-Cherepkov** [comment]
Hi @bvobart,

Thanks a lot for pointing out the inconsistency. We have fixed it in the recent commit: [e6cc98e5363eecd00e5a70ac08a09f98de4c7db7](https://github.com/yandex-research/navigan/commit/e6cc98e5363eecd00e5a70ac08a09f98de4c7db7).
