### ISSUE TITLE
Missing `torch_tools` dependency from requirements.txt

### ISSUE THREAD

**Issue by bvobart** [yandex-research/navigan#2]
Hi, it's me again, same guy who reported #1 

I noticed that Pylint reports the `torch_tools` import to be undefined. I can't find the dependency where this import is supposed to come from either and it does not seem to be included in PyTorch. Which library does this import come from? And can you add it to the requirements.txt as well? Thanks!

https://github.com/yandex-research/navigan/blob/e6cc98e5363eecd00e5a70ac08a09f98de4c7db7/trainer.py#L7

**Comment by anvoynov** [comment]
Hi @bvobart 
please check it in the project root: https://github.com/yandex-research/navigan/tree/master/torch_tools

**Comment by bvobart** [comment]
Ahhh so it's just a local module, thought I had checked that. Thanks for the clarification! I'll close this issue then. 

Still a bit annoying that Pylint tends to have trouble recognising imports from local modules such as this one. Then again, that's probably a problem with Pylint that I've been running into in other projects as well.
