### ISSUE TITLE
colab demo

### ISSUE THREAD

**Issue by molo32** [yandex-research/navigan#3]
please add colab demo

**Comment by ucalyptus2** [comment]
@molo32 here you go
https://colab.research.google.com/drive/1Yk98eFWp3luDIvkur1xWWbO1a2soxZdG?usp=sharing
cc @Anton-Cherepkov @anvoynov

**Comment by anvoynov** [comment]
Hi, @forkbabu thanks a lot for the demo!
If you don't mind, can we add the collab (with an attribution to you) to the readme?

**Comment by Anton-Cherepkov** [comment]
Hi @molo32,
Now colab demo is available [here](https://colab.research.google.com/drive/15aanLPN6_T2SHp0oQh3stIuESSfpNGuv?usp=sharing).

Thanks for you interest in our project.
