### ISSUE TITLE
injecting a 18x512 latent in yor model

### ISSUE THREAD

**Issue by yaseryacoob** [yandex-research/navigan#6]
I am trying to inject a specific stylegan2 latent 18x512 to your model. How can I do that?

**Comment by Anton-Cherepkov** [comment]
Hello @yaseryacoob,
You can pass a [BATCH x 18 x 512] tensor into [StyleGAN2Wrapper's forward](https://github.com/yandex-research/navigan/blob/e910fe5d60c9bf62dc2b997da0085cf58da73d84/models/gan_load.py#L54) method with argument `input_is_latent=True`.

**Comment by yaseryacoob** [comment]
It worked as you described. Much appreciated. Thanks for sharing your work!
